- src/components/option-separator/README.md
> docs(OptionSeparator): add docs

- package-lock.json
- src/components/logo/README.md
> docs(Logo): add basic readme of Logo

- package-lock.json
- package.json
Fix for #179 
Found solution from [here](https://github.com/gatsbyjs/gatsby/issues/864#issuecomment-297744295).
> chore(package-script): update develop script

- src/components/row/README.md
> chore(Row): add gutter prop

- src/components/card/README.md
- src/components/card/index.js
I missed to change the title caption's type...
> Change proptype of titleCaption of Card

- src/components/section/index.js
It's in the readme, but it wasn't implemented until now.
> fix(Section): add customizable classNames

- src/components/accordion/README.md
- src/components/accordion/index.js
I will put all the node type changes of components within one pull request finally.
> Change component string propt types to node for i18n

- src/components/confirmation/README.md
- src/components/confirmation/index.js
- src/layouts/index.js
- src/pages/confirmations.js
- src/postcss/main.css
- src/postcss/pages/confirmations.css
This fixes #217 issue. 
This PR is related to [PR 1364](https://github.com/purposeindustries/content-editor/pull/1364) on content-editor repo. We started the refact there, but than we introduced a more generic solution here.
> feat(confirm): Implement confirmation with example

- src/pages/avatars.js
> fix: Separate logo and profile in avatar editor

- src/components/row/README.md
- src/components/row/index.js
Extend the row component with a className prop for more accurate style targeting.
> add className prop

- src/components/modals/index.js
- src/pages/modals.js
- src/postcss/modal.css
- src/postcss/variables.css
- Implement auto scroll for modal in calse of `hasAutoHeight` enabled.
- Disable scroll of body if modal open.
- Implement modal `tileCaption`
> Feat(modal): scroll

- src/components/dropdown/index.js
- src/components/select/index.js
- src/postcss/select.css
I added className prop to select wrapper element for more accurate css targeting.
> feat(select): add classname to select + gray out unselected dropdown text

- circle.yml
when https://github.com/purposeindustries/hubot/pull/22 happens
> ignore e2e in force builds

- .circleci/config.yml
Even though I thought it's circleci's faults that I cannot match certain tag: https://github.com/purposeindustries/intellyo-application-design-system/pull/353, i realized it was our fault:https://github.com/purposeindustries/hubot/pull/27
But the regex should be wrapped in quotes.
> matching tag on circleci

- .circleci/config.yml
separate pre version deploy and proper version deploy
> separate pre version deploy

- src/components/list/dragSort.js
- src/postcss/list.css
> fix(list): enable user select

- README.md
If something is unclear, please let me know.
> docs: release and deploy docs

- .circleci/config.yml
Create and upload the tar.gz for preversions which are visible on the release page: https://github.com/purposeindustries/intellyo-application-design-system/releases
> create and upload release.tar.gz for preversions

- .circleci/config.yml
So next time I wont put my configuration to the wrong section.
@molnosikristof haha the duplicated code can be pain :)
> ci(circleci.yml): remove release commands from nightly builds

- src/components/avatar-card/README.md
- src/components/avatar-card/index.js
- src/pages/avatars.js
you can render your own avatar inside the avatar card.
> feat(avatar card): add render avatar prop.

- .circleci/config.yml
> ci: update notification url

- src/components/loading-button/README.md
- src/components/loading-button/index.js
[TP9960](https://purposeindustriesgmbh.tpondemand.com/RestUI/Board.aspx#page=feature/9960&appConfig=eyJhY2lkIjoiMTA1MTA5MDU0OEY2QTUyQjlFM0JCODkwRjYwQUVGMEIifQ==)
> feat(loading button): add disabled prop

- src/components/tile/README.md
- src/components/tile/index.js
- src/postcss/avatar.css
- src/postcss/tile.css
- src/postcss/variables.css
To make tile aligned with avatar sizes.
> feat(tile): add normal size

- .circleci/config.yml
Change confusing, duplicated name.
> chore: rename nihglty build e2e tests

- src/components/avatar-editor/index.js
Let avatar accept node as label. This makes the translations much easier.
> feat: accept node in avatar editor as button label

- src/components/input/index.js
Let `alwaysRenderSuggestions` be passed to the autocomplete component
> feat: add `alwaysRenderSuggestions` to input autocomplete

- src/components/option/index.js
ids tend to be number, let's make it possible using them.
> fix: add number as accepted option's value

- src/components/dropdown/index.js
Breaking change: supporting single option in multiselect
> feat: allow single item in multiselect

- src/components/accordion/index.js
You can use it for states and such.
> feat: customizable className for AccordionItem

- package.json
moving off from our registry, starting using the global one.
> chore: use the global registry

- src/components/caption/index.js
> feat: adding style props to caption

- src/components/checkbox/index.js
- src/pages/select.js
- src/postcss/checkbox.css
disabling checkbox wasn't possible until NOW.
> feat: add disabled checkbox state
