src/postcss/button.css
Fix for #215.
I checked every component by hand to find missing font-family rules. It seemed to me that only `Button` needed the rule, but pls let me know if you find one.
=> fix(Button): set font-family explicitly

e2e/utils/visual-regression.js, wdio.conf.js
It's up for a debate, but passing the `__dirname` every time seems like too much hassle for me, what do you think about this? the `testDirPath` already added to the browser so we don't need to pass the `__dirname`.
=> feat: store test file name

src/postcss/button.css
Norbi complained about not having the same heights between components. Setting back `box-sizing: border-box;` fixed the issue. Only the Button component used `box-sizing: content-box;`.
=> fix(Button): set box-sizing to border-box

.npmignore
I even increased the npm package size limit to 50MB but still, the publish failed.
Then i realized the e2e assets (images, test results, test files, reference images, diffs) were part of the package.
=> exclude e2e assets from npm

src/components/button/README.md, src/components/button/index.js
`Button` didn't pass down `type` prop until now.
=> fix(Button): add type prop to button

src/components/overlay-trigger/README.md
Component does not accept "placement" prop, so remove it from the example. This fixes #248 issue.
=> docs(overlayTrigger): fix misleading example

src/components/table/README.md
Column's name property description is more clear now, as it introduces name as "key of the data". This fixes #178 issue.
=> docs(columns): Change column's description

README.md, package.json, src/components/index.js, src/components/tile/README.md, src/components/tile/index.js, src/layouts/index.js, src/pages/tiles.js, src/postcss/main.css, src/postcss/tile.css
Implement a generic tile component, which can contain image, icon or solid color with 3 different size and 3 different shape like this:
=> Feat (tile): implement generic tile

src/components/index.js, src/components/modals/index.js
- fix the missing export of confirmation 
- overwrite `Rodal` default 240px height if FEF modal `hasAutoHeight` is `true`
=> Fix/(confirmation + modal): fix missing export, autoheight

package.json, src/components/overlay-trigger/index.js
Popovers will not close on clicking into them, only if you click outside.
Breaking change, as after introducing this bug-fix some popovers will not close automagically on CE.
=> fix (overlay trigger): implement click outside

src/components/multiselect/README.md, src/components/multiselect/index.js, src/pages/select.js, src/postcss/multiselect.css
Enable the multiselect to set the word "selected" to some translation. The space between the the number and another note could only be solved by css.
=> feat(multiselect): add selected label prop for i18n

src/components/tab-panel/index.js
`<TabPanel />` shouldn't return any child, which has the value of `null`. Therefore we need to use `React.Children.toArray()`, which removes the `null` elements from `this.props.children`.
Reference can be found [here](https://github.com/facebook/react/issues/4867#issuecomment-143061047).
=> fix(TabPanel): add toArray to be able to filter out null children

.circleci/config.yml
circleci is soo kind it wrongly sets the environment variable. even though I'm building the tag, it sets the `CIRCLE_BRANCH` env.
So I added the branch to the tag: `$CIRCLE_TAG$CIRCLE_BRANCH`
I could have replaced tag with branch but if they fix in the future, our code will be compatible with that one as well.
=> match tag and branch in deploy

package-lock.json, src/components/overlay-trigger/index.js
without this, every time we click on anywhere in the application, we
enforce all the rendered popovers (all the tooltips, popovers, dropdowns) to re-render themselves unnecessarily.
cc @oroce @gazdagergo
=> fix(popover): call deactivate on clickoutside only if opened

CHANGELOG.md, package.json
the version script was something I was completely unaware of. As it turned out ([docs](https://docs.npmjs.com/cli/version)) if you run `npm version <release type>` the `version` script in your package.json will be called after the version is bumped but before `git commit` is invoked.
I wasn't the genius who came up with this script, I found this here: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#with-npm-version
=> generate changelog

src/components/overlay-trigger/index.js
It could happen that the isActive state property becomes true after a certain delay so I can't remove the timeout listener based on this because I'd like to really deactivate it (shut the timer down) no matter if it's really active or just waiting for becoming active when the timeout listener fires.
The program without this patch can lead to unexpected scenarios when I hover over on the element (which activates the timer because it should appear with delay) and it appears after the delay however I've already left the element with the mouse.
=> fix(overlay trigger): remove timer on deactivate whatever the state is.

.circleci/config.yml, package.json
So the idea is the following:
- Each tag should contain a CHANGES.md which contains the changes we did in that tag (actually that's a diff of the previous version and this one)
- CHANGELOG.md contains all the changes of all the versions. It should be pushed into the master.
=> chore: generating changes and changelog

.circleci/config.yml
`npm view` uses npm to look up the version. Which means the it'll be the latest published but we need the version which is present in the package.json
`npm i -g npm@latest` is needed to make sure we have the [`npx`](https://www.npmjs.com/package/npx)
=> ci(rls generation): stop using `npm view`

.circleci/config.yml
Let's start creating new tag, called `vLATEST`, it won't be pushed to npm and won't be deployed. Changelog will ignore it since it wont match the semver.
But we can test the latest release (`vLATEST`) and the next planned one (`master`). 
fyi @ruffle1986
=> ci: always create latest tag and run e2e test

.circleci/config.yml
I tried multiple options but I was unable to run builds for latest, I raised a question in circleci's discussion platform: https://discuss.circleci.com/t/running-nightly-on-a-specified-git-tag/22406
Let's hope they will get back to me with a solution and I can re-enable this feature because it would handy having this.
=> ci: turn off nightly build for latest tag

src/components/dropdown-item/index.js
we tend to use `id` which is a number as value. it doesn't make any sense to convert to string and convert it back to number.
=> fix: allow number as dropdownitem's value

src/components/dropdown-item/index.js
What we were looking for is `oneOfType`
=> fix: PropTypes.oneOf expects concrete value, not another PropType

src/components/loading-button/index.js
It makes sense to pass icon for the LoadingButton if it isn't in loading state.
=> feat: passing icon to the LoadingButton in non loading state
